--- 
format: 1
handler: 
  commit: ff63ba97fb3d9d777216470667ce00d4b4780219
  branch: "2.4"
lock: false
repository_class: Piston::Git::Repository
repository_url: git://github.com/silverstripe/sapphire.git
