<?php
// $site_pages = array(1 => "Landfill", 2 => "Landmines", 3 => "Landed Gentry", 4 => "Disney Land");
// $site_keywords = array(1 => "tip, dump", 3 => "toffs");

$query		= isset($_GET['q']) ? $_GET['q'] : '';
$callback	= isset($_GET['callback']) ? $_GET['callback'] : '';
$results	= array();
$count		= 0;

// Cache of page titles and keywords is generated by /code/mysite/AtoZPage.php
include_once('../cache/autosuggest_list.php');

$query_words		= explode(' ', $query);
$query_words_count	= count($query_words);
// echo "$query_words_count";

foreach ($site_pages as $ID => $site_page){
	$match_count = 0;
	foreach($query_words as $query_word){
		if($query_word != ''){
			$search_string = (isset($site_keywords[$ID])) ? $site_page.' '.$site_keywords[$ID] : $site_page;
		}
		if (stripos($search_string, $query_word) !== false){$match_count++;}
	}
	$results[$ID] = ($match_count == $query_words_count) ? 1 : 0;
	
}

header('Cache-Control: no-cache, must-revalidate');
header('Expires: Mon, 1 Sat 2000 00:00:00 GMT');
header('Content-type: text/javascript; charset=utf-8');

echo $callback.' && '.$callback.'(["'.$query.'",[';

if (strlen($query)>1){

	$exact_match_id = array_nsearch($query, $site_pages);
	if($exact_match_id !== false){
		echo '["'.$site_pages[$exact_match_id].'","'.$site_urls[$exact_match_id].'","'.$count.'"]';
		$count++;
	}

	foreach ($site_pages as $site_id => $page_name){
		if($results[$site_id] == 1 && $site_id != $exact_match_id){
			if($count>0){echo ',';}
			echo '["'.$page_name.'","'.$site_urls[$site_id].'","'.$count.'"]';
			$count++;
		}
	}
}

echo ']])';
die();

function array_nsearch($needle, array $haystack) {
	$it = new IteratorIterator(new ArrayIterator($haystack));
	foreach($it as $key => $val) {
		if(strcasecmp($val,$needle) === 0) {
			return $key;
		}
	}
	return false;
} 
?>